sudo: false

language: node_js
node_js:
  - 6
  - 7

branches:
  only:
    - master

script:
  - yarn test:coverage

cache: yarn

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

notifications:
  slack: whiplashmerch:FOOw6JgjbfJEYI8DxCzXSfJo
  webhooks: https://coveralls.io/webhook?repo_token=RLeRWOziIq1pxmhc3OSlPlD069LqB9qDN
