sudo: false

language: node_js
node_js:
  - 6
  - 7

branches:
  only:
    - master

script:
  - yarn test:coverage

cache: yarn

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

notifications:
  slack: whiplashmerch:FOOw6JgjbfJEYI8DxCzXSfJo
  webhooks: https://coveralls.io/webhook?repo_token=RLeRWOziIq1pxmhc3OSlPlD069LqB9qDN
